// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesListed.Models;

namespace MoviesListed.Migrations
{
    [DbContext(typeof(movieContext))]
    [Migration("20210428064751_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesListed.Models.Lists", b =>
                {
                    b.Property<string>("ListsID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("mTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListsID");

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            ListsID = "A",
                            mTitle = "Action"
                        },
                        new
                        {
                            ListsID = "C",
                            mTitle = "Crime"
                        },
                        new
                        {
                            ListsID = "D",
                            mTitle = "Drama"
                        },
                        new
                        {
                            ListsID = "H",
                            mTitle = "Horror"
                        },
                        new
                        {
                            ListsID = "CO",
                            mTitle = "Comedy"
                        });
                });

            modelBuilder.Entity("MoviesListed.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListsID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<double?>("Runtime")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("ListsID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Actors = "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown, etc",
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            ListsID = "D",
                            Rating = 9.1999999999999993,
                            Runtime = 3.2200000000000002,
                            Title = " The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 5,
                            Actors = "Tom Hanks, Tom Sizemore, Edward Burns, Barry Pepper, Adam Goldberg, etc",
                            Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
                            ListsID = "D",
                            Rating = 8.5999999999999996,
                            Runtime = 2.4900000000000002,
                            Title = "Saving Private Ryan",
                            Year = 1998
                        },
                        new
                        {
                            MovieId = 4,
                            Actors = "Gregory Peck, John Megna, Frank Overton, Rosemary Murphy, Ruth White, etc",
                            Description = "Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his children against prejudice.",
                            ListsID = "D",
                            Rating = 8.1999999999999993,
                            Runtime = 2.0899999999999999,
                            Title = "To Kill a Mockingbird",
                            Year = 1962
                        },
                        new
                        {
                            MovieId = 2,
                            Actors = "Tom Hanks, Tim Allen, Annie Potts, Tony Hale, Keegan-Michael Key, etc",
                            Description = "Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woody's slight detour leads him to his long-lost friend Bo Peep. As Woody and Bo discuss the old days, they soon start to realize that they're worlds apart when it comes to what they want from life as a toy.",
                            ListsID = "C",
                            Rating = 4.5,
                            Runtime = 1.3999999999999999,
                            Title = "Toy Story 4",
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 3,
                            Actors = "Bruce Allpress, Sean Astin, John Bach, Sala Baker, Cate Blanchett, etc",
                            Description = "Frodo and Sam (Sean Astin) discover they are being followed by the mysterious Gollum. Aragorn (Viggo Mortensen), the Elf archer Legolas and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman's deadly spell.",
                            ListsID = "A",
                            Rating = 13.0,
                            Runtime = 3.4300000000000002,
                            Title = "The Lord of the Rings: The Two Towers",
                            Year = 2002
                        });
                });

            modelBuilder.Entity("MoviesListed.Models.Movie", b =>
                {
                    b.HasOne("MoviesListed.Models.Lists", "Lists")
                        .WithMany()
                        .HasForeignKey("ListsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lists");
                });
#pragma warning restore 612, 618
        }
    }
}
